export const FETCH_TAXI_STARTED = 'FETCH_TAXI_STARTED';
export const FETCH_TAXI_SUCCESS = 'FETCH_TAXI_SUCCESS';
export const FETCH_TAXI_FAILED = 'FETCH_TAXI_FAILED';

export const FILTER_TAXIS = 'FILTER_TAXIS';
